# Generated by Django 5.2.13 on 2026-04-09 05:41

import blockauth.passkey.models
import django.core.validators
import django.db.models.deletion
import uuid6
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="OTP",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("identifier", models.CharField(db_index=True, help_text="Email or phone to send OTP", max_length=100)),
                ("code", models.CharField(max_length=12)),
                ("is_used", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "subject",
                    models.CharField(
                        choices=[
                            ("login", "Login"),
                            ("sign_up", "Signup"),
                            ("password_reset", "Password Reset"),
                            ("email_change", "Email Change"),
                            ("wallet_email_verification", "Wallet Email Verification"),
                        ],
                        max_length=30,
                    ),
                ),
            ],
            options={
                "verbose_name": "OTP",
                "db_table": "otp",
                "managed": True,
                "indexes": [models.Index(fields=["identifier", "subject"], name="otp_identif_3aeae4_idx")],
            },
        ),
        migrations.CreateModel(
            name="PasskeyChallenge",
            fields=[
                ("id", models.UUIDField(default=uuid6.uuid7, editable=False, primary_key=True, serialize=False)),
                (
                    "challenge",
                    models.CharField(
                        db_index=True, help_text="Base64URL-encoded challenge", max_length=255, unique=True
                    ),
                ),
                (
                    "challenge_type",
                    models.CharField(
                        choices=[("registration", "Registration"), ("authentication", "Authentication")],
                        help_text="Whether this is for registration or authentication",
                        max_length=20,
                    ),
                ),
                ("expires_at", models.DateTimeField(db_index=True, help_text="When this challenge expires")),
                ("is_used", models.BooleanField(default=False, help_text="Whether this challenge has been consumed")),
                (
                    "metadata",
                    models.JSONField(blank=True, default=dict, help_text="Additional data associated with challenge"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        help_text="User associated with this challenge (optional)",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Passkey Challenge",
                "verbose_name_plural": "Passkey Challenges",
                "db_table": "passkey_challenge",
                "managed": True,
                "indexes": [
                    models.Index(fields=["challenge"], name="passkey_challenge_idx"),
                    models.Index(fields=["expires_at"], name="passkey_expires_idx"),
                    models.Index(fields=["user", "challenge_type"], name="passkey_user_type_idx"),
                ],
            },
        ),
        migrations.CreateModel(
            name="PasskeyCredential",
            fields=[
                ("id", models.UUIDField(default=uuid6.uuid7, editable=False, primary_key=True, serialize=False)),
                (
                    "credential_id",
                    models.TextField(
                        db_index=True, help_text="Base64URL-encoded credential ID from authenticator", unique=True
                    ),
                ),
                ("public_key", models.TextField(help_text="Base64URL-encoded COSE public key")),
                (
                    "algorithm",
                    models.IntegerField(
                        default=-7, help_text="COSE algorithm identifier (e.g., -7 for ES256, -257 for RS256)"
                    ),
                ),
                (
                    "sign_count",
                    models.BigIntegerField(
                        default=0,
                        help_text="Signature counter to detect cloned authenticators",
                        validators=[django.core.validators.MinValueValidator(0)],
                    ),
                ),
                (
                    "aaguid",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="Authenticator model identifier (AAGUID as UUID string)",
                        max_length=36,
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="User-provided name for this credential (e.g., 'My iPhone')",
                        max_length=255,
                    ),
                ),
                (
                    "transports",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text="Supported transports: internal, usb, nfc, ble, hybrid",
                        validators=[blockauth.passkey.models.validate_transports],
                    ),
                ),
                (
                    "authenticator_attachment",
                    models.CharField(
                        blank=True,
                        choices=[("platform", "Platform"), ("cross-platform", "Cross-Platform")],
                        default="",
                        help_text="platform (built-in) or cross-platform (roaming)",
                        max_length=20,
                    ),
                ),
                (
                    "backup_eligible",
                    models.BooleanField(default=False, help_text="Whether credential can be backed up (BE flag)"),
                ),
                (
                    "backup_state",
                    models.BooleanField(default=False, help_text="Whether credential is currently backed up (BS flag)"),
                ),
                (
                    "is_discoverable",
                    models.BooleanField(
                        default=False, help_text="Whether this is a discoverable credential (resident key)"
                    ),
                ),
                (
                    "user_handle",
                    models.TextField(
                        blank=True, default="", help_text="Base64URL-encoded user handle for discoverable credentials"
                    ),
                ),
                (
                    "attestation_object",
                    models.TextField(
                        blank=True,
                        default="",
                        help_text="Base64URL-encoded attestation object (if attestation was requested)",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, help_text="When the credential was registered")),
                (
                    "last_used_at",
                    models.DateTimeField(
                        blank=True, help_text="When the credential was last used for authentication", null=True
                    ),
                ),
                ("is_active", models.BooleanField(default=True, help_text="Whether this credential is active")),
                (
                    "revoked_at",
                    models.DateTimeField(blank=True, help_text="When the credential was revoked", null=True),
                ),
                (
                    "revocation_reason",
                    models.CharField(blank=True, default="", help_text="Reason for revocation", max_length=255),
                ),
                (
                    "user",
                    models.ForeignKey(
                        help_text="User who owns this credential",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="passkey_credentials",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Passkey Credential",
                "verbose_name_plural": "Passkey Credentials",
                "db_table": "passkey_credential",
                "ordering": ["-created_at"],
                "managed": True,
                "indexes": [
                    models.Index(fields=["user", "is_active"], name="passkey_user_active_idx"),
                    models.Index(fields=["credential_id"], name="passkey_cred_id_idx"),
                    models.Index(fields=["last_used_at"], name="passkey_last_used_idx"),
                ],
            },
        ),
        migrations.CreateModel(
            name="TOTP2FA",
            fields=[
                ("id", models.UUIDField(default=uuid6.uuid7, editable=False, primary_key=True, serialize=False)),
                ("encrypted_secret", models.TextField(help_text="Encrypted TOTP secret (Base32-encoded internally)")),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("disabled", "Disabled"),
                            ("pending_confirmation", "Pending Confirmation"),
                            ("enabled", "Enabled"),
                        ],
                        default="disabled",
                        help_text="Current TOTP status",
                        max_length=30,
                    ),
                ),
                (
                    "algorithm",
                    models.CharField(default="sha1", help_text="Hash algorithm (sha1, sha256, sha512)", max_length=10),
                ),
                (
                    "digits",
                    models.PositiveSmallIntegerField(default=6, help_text="Number of digits in TOTP code (6 or 8)"),
                ),
                ("time_step", models.PositiveSmallIntegerField(default=30, help_text="Time step in seconds")),
                (
                    "backup_codes_hash",
                    models.JSONField(blank=True, default=list, help_text="List of hashed backup codes (SHA-256)"),
                ),
                (
                    "backup_codes_remaining",
                    models.PositiveSmallIntegerField(default=0, help_text="Number of unused backup codes remaining"),
                ),
                (
                    "failed_attempts",
                    models.PositiveSmallIntegerField(
                        default=0, help_text="Number of consecutive failed verification attempts"
                    ),
                ),
                (
                    "locked_until",
                    models.DateTimeField(
                        blank=True, help_text="Account is locked until this time due to failed attempts", null=True
                    ),
                ),
                (
                    "last_failed_at",
                    models.DateTimeField(blank=True, help_text="Timestamp of last failed verification", null=True),
                ),
                (
                    "last_used_counter",
                    models.BigIntegerField(
                        blank=True, help_text="Time counter of last successfully used code (prevents replay)", null=True
                    ),
                ),
                (
                    "last_verified_at",
                    models.DateTimeField(blank=True, help_text="When TOTP was last successfully verified", null=True),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, help_text="When TOTP was initially set up")),
                (
                    "enabled_at",
                    models.DateTimeField(blank=True, help_text="When TOTP was confirmed and enabled", null=True),
                ),
                ("updated_at", models.DateTimeField(auto_now=True, help_text="Last update timestamp")),
                (
                    "recovery_email_sent_at",
                    models.DateTimeField(blank=True, help_text="When recovery instructions were last sent", null=True),
                ),
                (
                    "user",
                    models.OneToOneField(
                        help_text="User who owns this TOTP configuration",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="totp_2fa",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "TOTP 2FA Configuration",
                "verbose_name_plural": "TOTP 2FA Configurations",
                "db_table": "totp_2fa",
                "managed": True,
                "indexes": [
                    models.Index(fields=["user"], name="totp_user_idx"),
                    models.Index(fields=["status"], name="totp_status_idx"),
                    models.Index(fields=["locked_until"], name="totp_locked_idx"),
                ],
            },
        ),
        migrations.CreateModel(
            name="TOTPVerificationLog",
            fields=[
                ("id", models.UUIDField(default=uuid6.uuid7, editable=False, primary_key=True, serialize=False)),
                ("success", models.BooleanField(help_text="Whether verification was successful")),
                (
                    "verification_type",
                    models.CharField(
                        choices=[("totp", "TOTP Code"), ("backup", "Backup Code")],
                        help_text="Type of code verified",
                        max_length=20,
                    ),
                ),
                (
                    "ip_address",
                    models.GenericIPAddressField(blank=True, help_text="IP address of the request", null=True),
                ),
                ("user_agent", models.TextField(blank=True, default="", help_text="User agent of the request")),
                (
                    "failure_reason",
                    models.CharField(
                        blank=True, default="", help_text="Reason for failure if applicable", max_length=50
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, db_index=True, help_text="When the verification attempt occurred"
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        help_text="User who attempted verification",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="totp_verification_logs",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "TOTP Verification Log",
                "verbose_name_plural": "TOTP Verification Logs",
                "db_table": "totp_verification_log",
                "ordering": ["-created_at"],
                "managed": True,
                "indexes": [
                    models.Index(fields=["user", "created_at"], name="totp_log_user_time_idx"),
                    models.Index(fields=["success", "created_at"], name="totp_log_success_idx"),
                    models.Index(fields=["ip_address", "created_at"], name="totp_log_ip_idx"),
                ],
            },
        ),
    ]
