# Generated by Django 5.1.4 on 2024-12-21 02:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='OTP',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('identifier', models.CharField(help_text='Email to send OTP', max_length=100)),
                ('otp_code', models.CharField(max_length=12)),
                ('is_used', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('subject', models.CharField(choices=[('login', 'Login'), ('sign_up', 'Signup'), ('password_reset', 'Password Reset'), ('email_change', 'Email Change')], max_length=30)),
            ],
            options={
                'verbose_name': 'OTP',
                'db_table': 'otp',
                'managed': True,
                'indexes': [models.Index(fields=['identifier', 'subject'], name='otp_identif_3aeae4_idx')],
            },
        ),
    ]
