# Generated by Django 5.1.4

import uuid
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('blockauth', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='otp',
            name='subject',
            field=models.CharField(choices=[('login', 'Login'), ('sign_up', 'Signup'), ('password_reset', 'Password Reset'), ('email_change', 'Email Change'), ('wallet_email_verification', 'Wallet Email Verification')], max_length=30),
        ),
        migrations.CreateModel(
            name='PasskeyChallenge',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('challenge', models.CharField(db_index=True, help_text='Base64URL-encoded challenge', max_length=255, unique=True)),
                ('challenge_type', models.CharField(choices=[('registration', 'Registration'), ('authentication', 'Authentication')], help_text='Whether this is for registration or authentication', max_length=20)),
                ('expires_at', models.DateTimeField(db_index=True, help_text='When this challenge expires')),
                ('is_used', models.BooleanField(default=False, help_text='Whether this challenge has been consumed')),
                ('metadata', models.JSONField(blank=True, default=dict, help_text='Additional data associated with challenge')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(blank=True, help_text='User associated with this challenge (optional)', null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Passkey Challenge',
                'verbose_name_plural': 'Passkey Challenges',
                'db_table': 'passkey_challenge',
            },
        ),
        migrations.CreateModel(
            name='PasskeyCredential',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('credential_id', models.TextField(db_index=True, help_text='Base64URL-encoded credential ID from authenticator', unique=True)),
                ('public_key', models.TextField(help_text='Base64URL-encoded COSE public key')),
                ('algorithm', models.IntegerField(default=-7, help_text='COSE algorithm identifier (e.g., -7 for ES256, -257 for RS256)')),
                ('sign_count', models.BigIntegerField(default=0, help_text='Signature counter to detect cloned authenticators')),
                ('aaguid', models.CharField(blank=True, default='', help_text='Authenticator model identifier (AAGUID as UUID string)', max_length=36)),
                ('name', models.CharField(blank=True, default='', help_text="User-provided name for this credential (e.g., 'My iPhone')", max_length=255)),
                ('transports', models.JSONField(blank=True, default=list, help_text='Supported transports: internal, usb, nfc, ble, hybrid')),
                ('authenticator_attachment', models.CharField(blank=True, choices=[('platform', 'Platform'), ('cross-platform', 'Cross-Platform')], default='', help_text='platform (built-in) or cross-platform (roaming)', max_length=20)),
                ('backup_eligible', models.BooleanField(default=False, help_text='Whether credential can be backed up (BE flag)')),
                ('backup_state', models.BooleanField(default=False, help_text='Whether credential is currently backed up (BS flag)')),
                ('is_discoverable', models.BooleanField(default=False, help_text='Whether this is a discoverable credential (resident key)')),
                ('user_handle', models.TextField(blank=True, default='', help_text='Base64URL-encoded user handle for discoverable credentials')),
                ('attestation_object', models.TextField(blank=True, default='', help_text='Base64URL-encoded attestation object (if attestation was requested)')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='When the credential was registered')),
                ('last_used_at', models.DateTimeField(blank=True, help_text='When the credential was last used for authentication', null=True)),
                ('is_active', models.BooleanField(default=True, help_text='Whether this credential is active')),
                ('revoked_at', models.DateTimeField(blank=True, help_text='When the credential was revoked', null=True)),
                ('revocation_reason', models.CharField(blank=True, default='', help_text='Reason for revocation', max_length=255)),
                ('user', models.ForeignKey(help_text='User who owns this credential', on_delete=django.db.models.deletion.CASCADE, related_name='passkey_credentials', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Passkey Credential',
                'verbose_name_plural': 'Passkey Credentials',
                'db_table': 'passkey_credential',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='passkeychallenge',
            index=models.Index(fields=['challenge'], name='passkey_challenge_idx'),
        ),
        migrations.AddIndex(
            model_name='passkeychallenge',
            index=models.Index(fields=['expires_at'], name='passkey_expires_idx'),
        ),
        migrations.AddIndex(
            model_name='passkeychallenge',
            index=models.Index(fields=['user', 'challenge_type'], name='passkey_user_type_idx'),
        ),
        migrations.AddIndex(
            model_name='passkeycredential',
            index=models.Index(fields=['user', 'is_active'], name='passkey_user_active_idx'),
        ),
        migrations.AddIndex(
            model_name='passkeycredential',
            index=models.Index(fields=['credential_id'], name='passkey_cred_id_idx'),
        ),
        migrations.AddIndex(
            model_name='passkeycredential',
            index=models.Index(fields=['last_used_at'], name='passkey_last_used_idx'),
        ),
    ]
