# Generated by Django 5.1.4 on 2025-02-26 17:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blockauth', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='otp',
            old_name='otp_code',
            new_name='code',
        ),
    ]
