# Generated by Django 5.1.4 - Add validators to passkey fields

import django.core.validators
from django.db import migrations, models

import blockauth.passkey.models


class Migration(migrations.Migration):

    dependencies = [
        ('blockauth', '0002_passkey'),
    ]

    operations = [
        migrations.AlterField(
            model_name='passkeycredential',
            name='sign_count',
            field=models.BigIntegerField(
                default=0,
                validators=[django.core.validators.MinValueValidator(0)],
                help_text='Signature counter to detect cloned authenticators'
            ),
        ),
        migrations.AlterField(
            model_name='passkeycredential',
            name='transports',
            field=models.JSONField(
                blank=True,
                default=list,
                validators=[blockauth.passkey.models.validate_transports],
                help_text='Supported transports: internal, usb, nfc, ble, hybrid'
            ),
        ),
    ]
